parameters:
  pathDriver: 'target/chromedriver/83.0.4103.39/chromedriver_win32/chromedriver.exe'
  numbers: '5155'
  message: 'Hola, recuerda que hoy Jueves 16 de Julio es el Taller de "Introducción a Grid Layout" a las 7pm.
Únete al taller online aquí : https://bit.ly/3fCVtPw
Contraseña : gridlayout
Este mensaje es informativo. No es necesario responder.
#YoMeQuedoEnCasa'